/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lenz.guikalkulator;

/**
 *
 * @author excee
 */
public class KalkulatorBD extends javax.swing.JFrame {
    
Double D1, D2, sisi, sisiket, A, B, C, T, luaspersegi, luasbelahket, luasseg, kelpersegi, kelbelahket, kelseg;

    /**
     * Creates new form KalkulatorBD
     */
    public KalkulatorBD() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTSSS = new javax.swing.JLabel();
        TXTA = new javax.swing.JLabel();
        TFA = new javax.swing.JTextField();
        TXTB = new javax.swing.JLabel();
        TFB = new javax.swing.JTextField();
        TXTC = new javax.swing.JLabel();
        TFC = new javax.swing.JTextField();
        TXTHasilSeg = new javax.swing.JLabel();
        TXTluasSSS = new javax.swing.JLabel();
        TFLuasSeg = new javax.swing.JTextField();
        TFD2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txthasilpersegi = new javax.swing.JLabel();
        TFKelSeg = new javax.swing.JTextField();
        txthasilpp = new javax.swing.JLabel();
        btnhitungpp = new javax.swing.JButton();
        txthasilluaspp = new javax.swing.JLabel();
        TFhasilLbelahket = new javax.swing.JTextField();
        TXThasilkelilingpp = new javax.swing.JLabel();
        TFhasilkelbelahket = new javax.swing.JTextField();
        TXTluaspersegi = new javax.swing.JLabel();
        TFhasilluaspersegi = new javax.swing.JTextField();
        txtkalkulator = new javax.swing.JLabel();
        txtpersegi = new javax.swing.JLabel();
        areasisipersegi = new javax.swing.JLabel();
        fieldsisipersegi = new javax.swing.JTextField();
        txtBelahKetupat = new javax.swing.JLabel();
        TXTD1 = new javax.swing.JLabel();
        TFD1 = new javax.swing.JTextField();
        TXTD2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TFhasilkelpersegi = new javax.swing.JTextField();
        TXTT = new javax.swing.JLabel();
        TFT = new javax.swing.JTextField();
        TXTSisket = new javax.swing.JLabel();
        TFsisket = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TXTSSS.setBackground(new java.awt.Color(102, 0, 102));
        TXTSSS.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTSSS.setForeground(new java.awt.Color(0, 204, 204));
        TXTSSS.setText("Segitiga Sama Sisi");

        TXTA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTA.setText("Masukkan A");

        TFA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFAActionPerformed(evt);
            }
        });

        TXTB.setText("Masukkan B(alas)");

        TFB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBActionPerformed(evt);
            }
        });

        TXTC.setText("Masukkan C");

        TXTHasilSeg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TXTHasilSeg.setText("Hasil");

        TXTluasSSS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTluasSSS.setText("Luas");

        TFD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFD2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Keliling");

        txthasilpersegi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txthasilpersegi.setText("Hasil");

        TFKelSeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFKelSegActionPerformed(evt);
            }
        });

        txthasilpp.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txthasilpp.setText("Hasil");

        btnhitungpp.setBackground(new java.awt.Color(153, 255, 153));
        btnhitungpp.setText("Hitung");
        btnhitungpp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungppActionPerformed(evt);
            }
        });

        txthasilluaspp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txthasilluaspp.setText("Luas");

        TFhasilLbelahket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhasilLbelahketActionPerformed(evt);
            }
        });

        TXThasilkelilingpp.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXThasilkelilingpp.setText("Keliling");

        TXTluaspersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTluaspersegi.setText("Luas");

        txtkalkulator.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        txtkalkulator.setForeground(new java.awt.Color(0, 204, 204));
        txtkalkulator.setText("KalkulatorKU");

        txtpersegi.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtpersegi.setForeground(new java.awt.Color(0, 204, 204));
        txtpersegi.setText("Persegi");

        areasisipersegi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        areasisipersegi.setText("Masukkan Sisi");

        fieldsisipersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldsisipersegiActionPerformed(evt);
            }
        });

        txtBelahKetupat.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBelahKetupat.setForeground(new java.awt.Color(0, 204, 204));
        txtBelahKetupat.setText("BelahKetupat");

        TXTD1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TXTD1.setText("D1");

        TFD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFD1ActionPerformed(evt);
            }
        });

        TXTD2.setText("D2");

        jLabel1.setText("Keliling");

        TFhasilkelpersegi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFhasilkelpersegiActionPerformed(evt);
            }
        });

        TXTT.setText("Masukkan T");

        TFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFTActionPerformed(evt);
            }
        });

        TXTSisket.setText("Sisi Ket");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(txtBelahKetupat)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(TXTluaspersegi))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFhasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFhasilkelpersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtpersegi)
                                .addGap(20, 20, 20)))
                        .addGap(8, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtkalkulator)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(areasisipersegi)
                                        .addComponent(fieldsisipersegi, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txthasilpersegi)
                                .addGap(79, 79, 79)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(TXTSSS))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(TXTHasilSeg)))
                        .addGap(41, 44, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTC)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFA, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFC, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TXTA, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXTB)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(TFB)
                                        .addComponent(TFT, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(TXTT, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(TXTD1)
                        .addGap(57, 57, 57)
                        .addComponent(TXTD2)
                        .addGap(54, 54, 54)
                        .addComponent(TXTSisket))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TXThasilkelilingpp)
                                    .addComponent(txthasilluaspp))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TFhasilkelbelahket, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFhasilLbelahket, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TFD1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TFD2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txthasilpp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFsisket, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(94, 94, 94)
                .addComponent(btnhitungpp, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXTluasSSS)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFKelSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TFLuasSeg, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(txtBelahKetupat)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TXTD1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTSisket)
                                    .addComponent(TXTD2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TFD2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TFsisket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthasilpp)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFhasilLbelahket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthasilluaspp))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TFhasilkelbelahket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TXThasilkelilingpp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(txtkalkulator, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TXTHasilSeg))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TXTSSS)
                                    .addComponent(txtpersegi))
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TXTA)
                                            .addComponent(TXTB)
                                            .addComponent(areasisipersegi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TFA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldsisipersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(TFB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TXTT)
                                            .addComponent(TXTC)
                                            .addComponent(txthasilpersegi))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TFT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(TFhasilluaspersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(TXTluaspersegi)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(TFhasilkelpersegi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TXTluasSSS)
                    .addComponent(TFLuasSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TFKelSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnhitungpp)
                .addGap(108, 108, 108))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFAActionPerformed

    private void TFBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBActionPerformed

    private void TFD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFD2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFD2ActionPerformed

    private void btnhitungppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungppActionPerformed
       
        D1 = Double.parseDouble(TFD1.getText());
        D2 = Double.parseDouble(TFD2.getText());
        sisiket = Double.parseDouble(TFsisket.getText()); 

      
        luasbelahket = D1 * D2 / 2;
        kelbelahket = 4 * sisiket;

  
        TFhasilLbelahket.setText(String.valueOf(luasbelahket));
        TFhasilkelbelahket.setText(String.valueOf(kelbelahket));

   
        sisi = Double.parseDouble(fieldsisipersegi.getText());
        
        luaspersegi = sisi * sisi;
        kelpersegi = 4 * sisi;

       
        TFhasilluaspersegi.setText(String.valueOf(luaspersegi));
        TFhasilkelpersegi.setText(String.valueOf(kelpersegi));

      
        A = Double.parseDouble(TFA.getText());
        B = Double.parseDouble(TFB.getText());
        C = Double.parseDouble(TFC.getText());
        T = Double.parseDouble(TFT.getText());

        luasseg = (A * T) / 2;
        kelseg = A + B + C;

   
        TFLuasSeg.setText(String.valueOf(luasseg));
        TFKelSeg.setText(String.valueOf(kelseg));
        
 
 

    }//GEN-LAST:event_btnhitungppActionPerformed

    private void TFhasilLbelahketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhasilLbelahketActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhasilLbelahketActionPerformed

    private void fieldsisipersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldsisipersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldsisipersegiActionPerformed

    private void TFD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFD1ActionPerformed

    private void TFhasilkelpersegiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFhasilkelpersegiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFhasilkelpersegiActionPerformed

    private void TFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFTActionPerformed

    private void TFKelSegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFKelSegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFKelSegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KalkulatorBD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KalkulatorBD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TFA;
    private javax.swing.JTextField TFB;
    private javax.swing.JTextField TFC;
    private javax.swing.JTextField TFD1;
    private javax.swing.JTextField TFD2;
    private javax.swing.JTextField TFKelSeg;
    private javax.swing.JTextField TFLuasSeg;
    private javax.swing.JTextField TFT;
    private javax.swing.JTextField TFhasilLbelahket;
    private javax.swing.JTextField TFhasilkelbelahket;
    private javax.swing.JTextField TFhasilkelpersegi;
    private javax.swing.JTextField TFhasilluaspersegi;
    private javax.swing.JTextField TFsisket;
    private javax.swing.JLabel TXTA;
    private javax.swing.JLabel TXTB;
    private javax.swing.JLabel TXTC;
    private javax.swing.JLabel TXTD1;
    private javax.swing.JLabel TXTD2;
    private javax.swing.JLabel TXTHasilSeg;
    private javax.swing.JLabel TXTSSS;
    private javax.swing.JLabel TXTSisket;
    private javax.swing.JLabel TXTT;
    private javax.swing.JLabel TXThasilkelilingpp;
    private javax.swing.JLabel TXTluasSSS;
    private javax.swing.JLabel TXTluaspersegi;
    private javax.swing.JLabel areasisipersegi;
    private javax.swing.JButton btnhitungpp;
    private javax.swing.JTextField fieldsisipersegi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtBelahKetupat;
    private javax.swing.JLabel txthasilluaspp;
    private javax.swing.JLabel txthasilpersegi;
    private javax.swing.JLabel txthasilpp;
    private javax.swing.JLabel txtkalkulator;
    private javax.swing.JLabel txtpersegi;
    // End of variables declaration//GEN-END:variables
}
